name: Test and Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: prantlf/setup-v-action@v4
    - run: make

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v7
    - uses: prantlf/setup-v-action@v4
    - run: make

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v7
    - uses: prantlf/setup-v-action@v4
    - run: cmd /c make.bat

  release:
    if: ${{ github.ref_name == 'master' }}
    needs:
      - linux
      - macos
      - windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: prantlf/publish-release-action@v2
      with:
        no-archives: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
